切换到新的Magisk模块安装脚本&修复MT6893识别问题&适配Scene调度配置&支持uninstall.sh
yc9559/uperf pull request #93
Opened 2022-04-09 11:18 UTC by railjty

### 1.Magisk模块安装脚本更新
便于支持新的模块指定的更新通道（Magisk v24.0加入），且对新的Magisk模块安装友好
### 2.修复MT6893识别问题
在Redmi Note 10 Pro China设备上出现大量报告识别出错的情况，经过提取prop发现，这些设备被错误设定为MT6893，为了支持这些设备，加入根据频率判断MT6893平台的代码。
与此同时，在Redmi K40 Gaming设备上发现，CPU7的scaling_available_frequencies和scaling_max_freq会在触发温度墙之后被锁定为2.6G。考虑到部分设备极度容易触发温度墙，故修改为cpuinfo_max_freq。同时，出现部分设备cpuinfo_max_freq被错误锁定为0000权限情况进行修复
### 3.适配Scene调度配置文件
根据Scene 5.2.0 PreRelease，在powercfg.sh中加入相关”底座模式（设定为performance模式）”“init模式（即为开机启动时的初始模式）”代码，且添加powercfg.json说明文件，简化使用Scene配置步骤
### 4.支持uninstall.sh
加入wait _until_login，支持彻底卸载模块

2022-04-09 11:19 UTC, railjty commented
抱歉一次提交如此之多，由于v2->v3更新间隔已经有半年以上，故总结提交

2022-04-11 10:53 UTC, yc9559 requested changes
请完成上述更改后，再提交合入

2022-04-11 10:53 UTC, yc9559 commented on magisk/script/setup.sh
> +    rm -rf /sdcard/yc/uperf
请不要删除用户配置

2022-04-11 10:53 UTC, yc9559 commented on magisk/script/setup.sh
> +echo "* Version: v3(22.04.04)"
版本22.04.09)

2022-04-11 10:53 UTC, yc9559 commented on magisk/script/initsvc.sh
> +wait_until_login
为何提前wait

2022-04-11 10:53 UTC, yc9559 commented on magisk/script/initsvc.sh
> +mv $USER_PATH/uperf.log $USER_PATH/uperf.log.bak
请同步04.09的更改

2022-04-11 10:53 UTC, yc9559 commented on magisk/script/setup.sh
> +magisk --install-module $BASEDIR/../sfanalysis-magisk.zip
用户此路径无文件

2022-04-11 10:53 UTC, yc9559 commented on magisk/service.sh
> +    rm $BASEDIR/logcat.log
请保留logcat

2022-04-11 10:53 UTC, yc9559 commented on magisk/system.prop
> +persist.sys.usap_pool_enabled=false
usap可减少fork耗时，为何关闭

2022-04-11 10:53 UTC, yc9559 commented on magisk/uninstall.sh
> +wait_until_login
早期版本有卸载脚本，但是早期magisk并非异步执行此脚本，导致卡开机，请考虑这个情况

2022-04-11 10:56 UTC, railjty commented on magisk/script/setup.sh
> +    rm -rf /sdcard/yc/uperf
OK

2022-04-11 10:56 UTC, railjty commented on magisk/uninstall.sh
> +wait_until_login
好的

2022-04-11 12:08 UTC, railjty commented on magisk/service.sh
> +    rm $BASEDIR/logcat.log
OK

2022-04-11 12:09 UTC, railjty commented on magisk/script/setup.sh
> +magisk --install-module $BASEDIR/../sfanalysis-magisk.zip
整合了sfanalysis的模块安装，将清除

2022-04-11 12:15 UTC, railjty commented on magisk/script/initsvc.sh
> +mv $USER_PATH/uperf.log $USER_PATH/uperf.log.bak
OK

2022-04-11 12:28 UTC, railjty commented on magisk/system.prop
> +persist.sys.usap_pool_enabled=false
这项功能较为耗费系统内存，实际体验提升也极为不明显，且大量usap32对Cortex A710目前影响可能不好。

2022-04-11 12:28 UTC, railjty commented on magisk/script/setup.sh
> +echo "* Version: v3(22.04.04)"
直接读取module.prop里面的或许更佳？

2022-04-11 12:30 UTC, railjty reviewed
Fixed as requested

2022-04-12 12:19 UTC, yc9559 requested changes
更正表述后合入

2022-04-12 12:19 UTC, yc9559 commented on magisk/uninstall.sh
> +    #wait_until_login
注释的原因是启用wait会卡开机吗，但是如果不wait执行到这可能data分区还没解密

2022-04-12 12:19 UTC, yc9559 commented on README.md
> +- 支持Magisk方式一键安装，版本不低于23.0
从magisk脚本来看，是20.4+

2022-04-12 12:19 UTC, yc9559 commented on README.md
> +- `string`，最基础的写入器。效果等同于`echo "val" > /path`。 **注意：为了提升性能，不会和echo一样清空原有内容**
写入前执行了lseek()，会从头开始写

2022-04-12 12:19 UTC, yc9559 commented on README.md
> +  (注：v3已经全面切换到powersave)
v3使用哪个内核调速器还未最终确定

2022-04-14 16:23 UTC, railjty commented on magisk/uninstall.sh
> +    #wait_until_login
可能开始有理解错误，这一步会解除注释

2022-04-14 16:24 UTC, railjty commented on README.md
> +- 支持Magisk方式一键安装，版本不低于23.0
确实需要按照脚本来，可以废除minMagisk=17000了

2022-04-14 16:24 UTC, railjty commented on README.md
> +  (注：v3已经全面切换到powersave)
会删除此行

2022-04-14 16:29 UTC, railjty commented
对于旧版本的Magisk，个人认为支持的意义已然不大，跟进最新的Magisk也能利用更多特性（比如Zygisk直接注入框架实现ssanalysis）

2022-04-15 10:36 UTC, yc9559 commented
此前使用zygisk实验过一些高级周期观测注入，可以不用换模板

2022-04-15 10:37 UTC, merged

2022-04-15 10:38 UTC, railjty commented
> 此前使用zygisk实验过一些高级周期观测注入，可以不用换模板

新的模板主要是方便进行管理器在线更新模块，而且Magisk官方文档已经完全基于新的模板